### ISSUE TITLE
sequelizeを別の何かにしたい

### ISSUE THREAD

**Issue by f1w3** [BOKURANO-OVERWATCH/WO-OW#2]

**Comment by t4t5u0** [comment]
候補
1. Prism
2. Drizzle

**Comment by raveuptonight** [comment]
Drizzle使ってみたいです（さかもとです）

**Comment by t4t5u0** [comment]
> Drizzle使ってみたいです

そしたらDrizzleで組みますか

**Comment by t4t5u0** [comment]
SQLiteやめたくなってきた。Drizzleに時刻もJSONをもない

Neonとかに乗せたいな

**Comment by raveuptonight** [comment]
https://qiita.com/nuko-suke/items/e940ff8ccde35d09f668

これですか、確かに便利そう

**Comment by t4t5u0** [comment]
(Neonも無償枠廃止の話があったような気がする)

**Comment by t4t5u0** [comment]
スキーマは移行完了
