### ISSUE TITLE
開発サイドのツールなどを統一する

### ISSUE THREAD

**Issue by f1w3** [BOKURANO-OVERWATCH/WO-OW#33]
今のところbunjsで実行する人が多そうなのでbunjsで統一したいが
bunjsを知らない人も居る為その辺を統一するなら説明を追加したい

またデプロイ先の問題(bunjsに対応してるしてない)もあるためそこも決めていきたい

**Comment by t4t5u0** [comment]
デプロイ環境も整い、Bunjsの統一するということになったので、閉じていいと思う
